apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: udemy_microservices/ticketing/expiration
          imagePullPolicy: Never
          env:
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            # to generate cliend id the same as our pod name
            # this will help us to read the logs of NATS
            # if we scale our ticketing service to multiple instances
            - name: NATS_CLIENT_ID
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-srv
